global ItfGestorTareas gestorTareas;
global ItfUsoRecursoTrazas recursoTrazas;
global String agentId;

/*Primera regla que se ejecutara. Solo se debe disparar una vez.
rule "Acciones Iniciales Explorador"
	when
		not (exists(Focus()))
		not (exists(MisObjetivos()))
	then
		TareaSincrona tarea1 = gestorTareas.crearTareaSincrona(InicializarInfoWorkMem.class);
   		tarea1.ejecutar( );
   		//TODO mirar que hace tarea 2
   		TareaSincrona tarea2 = gestorTareas.crearTareaSincrona(InicializarRobotStatus.class);
   		tarea2.ejecutar( );
   		recursoTrazas.aceptaNuevaTrazaEjecReglas(agentId," :REGLA " + drools.getRule().getName());
   		System.out.println( "\n"+agentId +"EJECUTO LA REGLA Acciones Iniciales\n\n" ); 
end

rule "Explorar Terreno"
	when
		focoActual : Focus(foco == null)
		obj: ExplorarTerreno();
		//peticionAgte: PeticionAgente( mensajePeticion == VocabularioRosace.MsgPeticionExplorar)
	then
		focoActual.set(obj);
		//TareaSincrona tarea = gestorTareas.crearTareaSincrona(ExplorarTerreno.class);
		//tarea.ejecutar();
		recursoTrazas.aceptaNuevaTrazaEjecReglas(agentId," :REGLA " + drools.getRule().getName());
		System.out.println("\n"+agentId +"EJECUTO LA REGLA Explorar Terreno\n\n");
		update(focoActual);
end