import icaro.infraestructura.entidadesBasicas.procesadorCognitivo.InformeDeTarea;
import icaro.infraestructura.recursosOrganizacion.recursoTrazas.ItfUsoRecursoTrazas;
import icaro.infraestructura.recursosOrganizacion.recursoTrazas.imp.componentes.InfoTraza;
import icaro.infraestructura.entidadesBasicas.procesadorCognitivo.*;
import icaro.infraestructura.patronAgenteCognitivo.procesadorObjetivos.gestorTareas.ItfGestorTareas;
import icaro.aplicaciones.SIDEMA.informacion.*;
import icaro.infraestructura.entidadesBasicas.procesadorCognitivo.Objetivo;
import icaro.aplicaciones.agentes.agenteNeutralizador.tareas.*;
import icaro.aplicaciones.agentes.agenteNeutralizador.objetivos*;
import java.lang.String;

global ItfGestorTareas gestorTareas;
global ItfUsoRecursoTrazas recursoTrazas;
global String agentId;

/*Primera regla que se ejecutara. Solo se debe disparar una vez.
rule "Acciones Iniciales Neutralizador"
	when
		not (exists(Focus()))
		not (exists(MisObjetivos()))
	then
		TareaSincrona tarea1 = gestorTareas.crearTareaSincrona(InicializarInfoWorkMem.class);
   		tarea1.ejecutar( );
   		//TODO mirar que hace tarea 2
   		TareaSincrona tarea2 = gestorTareas.crearTareaSincrona(InicializarRobotStatus.class);
   		tarea2.ejecutar( );
   		recursoTrazas.aceptaNuevaTrazaEjecReglas(agentId," :REGLA " + drools.getRule().getName());
   		System.out.println( "\n"+agentId +"EJECUTO LA REGLA Acciones Iniciales\n\n" ); 
end

rule "Desactivar Mina"
	when
		focoActual : Focus(foco == null)
		ordenCC: OrdenDesactivar( mensajeControl == VocabularioSIDEMA.MsgPeticionDesactivar, celdaMina:justificacion)
	then
		TareaSincrona tarea = gestorTareas.crearTareaSincrona(DesactivarMina.class);
		tarea.ejecutar(celdaMina);
		recursoTrazas.aceptaNuevaTrazaEjecReglas(agentId," :REGLA " + drools.getRule().getName());
		System.out.println("\n"+agentId +"EJECUTO LA REGLA Desactivar Mina\n\n");
end