global ItfGestorTareas gestorTareas;
global ItfUsoRecursoTrazas recursoTrazas;
global String agentId;

*Primera regla que se ejecutara. Solo se debe disparar una vez.
rule "Acciones Iniciales Centro de Control"
	when
		not (exists(Focus()))
		not (exists(MisObjetivos()))
	then
		TareaSincrona tarea1 = gestorTareas.crearTareaSincrona(InicializarInfoWorkMem.class);
   		tarea1.ejecutar( );
   		//TODO mirar que hace tarea 2
   		TareaSincrona tarea2 = gestorTareas.crearTareaSincrona(InicializarRobotStatus.class);
   		tarea2.ejecutar( );
   		recursoTrazas.aceptaNuevaTrazaEjecReglas(agentId," :REGLA " + drools.getRule().getName());
   		System.out.println( "\n"+agentId +"EJECUTO LA REGLA Acciones Iniciales\n\n" ); 
end

rule "Distribuir Terreno"
	when
		focoActual : Focus(foco == null)
		mapa : Mapa();
	then
		TareaSincrona tarea = gestorTareas.crearTareaSincrona(DistribuirTerreno.class);
		tarea.ejecutar(mapa);
		recursoTrazas.aceptaNuevaTrazaEjecReglas(agentId," :REGLA " + drools.getRule().getName());
		System.out.println("\n"+agentId +"EJECUTO LA REGLA Distribuir Terreno\n\n");